### ISSUE TITLE
Any plans for supporting vscode-neovim?

### ISSUE THREAD

**Issue by moqsien** [galkowskit/go-interface-annotations#7]
I wonder if there is any plan for supporting vscode-neovim or vscode-vim?

for example, special keys to invoke go-interface-annotations.

**Comment by galkowskit** [comment]
Hm, I think that is already supported by default keybindings? What this extension does is it uses VS Code's "Find References" and "Find Implementations" feature. I guess those keybindings should work the same. 🤔

**Comment by moqsien** [comment]
这是来自FoxMail邮箱的假期自动回复邮件。
 
您好，我是Mo-Qsien，最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复！

**Comment by moqsien** [comment]
> Hm, I think that is already supported by default keybindings? What this extension does is it uses VS Code's "Find References" and "Find Implementations" feature. I guess those keybindings should work the same. 🤔

Yep, I've got it.
The command codelens.showLensesInCurrentLine does meet the need.
Many thanks!
